version: "3.8"

services:
  mongoDB:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: qwe123
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 9010:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: qwe123
      ME_CONFIG_MONGODB_URL: mongodb://root:qwe123@mongoDB:27017/

  # app:
  #     build:
  #       dockerfile: ./DockerFile
  #       context: .
  #     command: tail -F /dev/nul
  #     depends_on:
  #       - mongoDB
  #     ports:
  #       - 9012:8081


volumes:
  mongodata: