# syntax=docker/dockerfile:1
FROM golang:1.19-alpine As build-env
WORKDIR /home/app
COPY . .
WORKDIR /home/app/test_line_dev
RUN go mod tidy
RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o ./app

FROM alpine
WORKDIR /app/
COPY --from=build-env /home/app/test_line_dev/app /app
COPY --from=build-env /home/app/config /app/config